export const items = {
  objetos: [
    "Roupa",
    "Peteca",
    "Chaveiro",
    "Barraca",
    "Apito",
    "Bola",
    "Corda",
    "Cadeira",
    "Laço",
    "Bandeira",
    "Boneca",
    "Celular",
    "Copo",
    "Controle",
    "Panela",
    "Teclado",
    "Café",
    "Xícara",
    "Tabuleiro",
    "Cobertor",
    "Caderno",
    "Chapéu",
    "Luva",
    "Vassoura",
    "Caixa",
    "Corrente",
    "Fone de ouvido",
    "TV"
  ],
  adjetivos: ["de ouro", "transparente", "brilhante", "futurista", "descartável", "exótico", "listrado", "quebrado", "de vidro", "coméstivel", "gosmento", "inquebrável", "de lã", "com pilha"],
};
